### ISSUE TITLE
Error after updating package: "__vite_ssr_import_2__.defu is not a function"

### ISSUE THREAD

**Issue by stenuto** [nuxt-modules/supabase#123]
I was admittedly being a bit careless in updating some npm packages and am now getting the following error:

**500**
___vite_ssr_import_2__.defu is not a function_

```
at ./node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.mjs:14:40
at fn (./node_modules/nuxt/dist/app/nuxt.mjs:148:27)
at Object.callAsync (./node_modules/unctx/dist/index.mjs:49:19)
at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:150:23)
at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:94:29)
at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:104:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:30:7)
at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
```

@nuxtjs/supabase v 0.3.0 somehow got installed so I tried rolling it back to 0.2.4 (the version my package.json showed in my last commit). That doesn't seem to be working either.

Any help?

**Comment by larbish** [comment]
Did you also update nuxt to the stable v3 ? Can you try to remove your `.nuxt`, `node-modules` folders and your lock file then install again ?
