### ISSUE TITLE
With module activated i got [500] useState is not defined . Fresh install

### ISSUE THREAD

**Issue by wojtekpiskorz** [nuxt-modules/supabase#190]
### Version
@nuxtjs/supabase: 
nuxt: 

### Reproduction Link
https://github.com/wojtekpiskorz/nuxt-playground

### Steps to reproduce
Fresh install of nuxt with ```npx nuxi init```
Install supabase module with
```npm install @nuxtjs/supabase --save-dev```

add module to nuxt config
```  modules: ['@nuxtjs/supabase'],```

run``` npm run dev```

### What is Expected?

Regular starter template with 2 warning regarding missing subabase .env credentials.

### What is actually happening?
After npm run dev when I go to localhost3000

```
[nuxt] [request error] [unhandled] [500] useState is not defined                                                                                             12:41:30 PM
  at Module.useSupabaseUser (./node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseUser.mjs:4:16)  
  at Object.setup (./node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.mjs:14:38)  
  at wrapper (./node_modules/nuxt/dist/app/nuxt.js:191:21)  
  at ./node_modules/nuxt/dist/app/nuxt.js:111:58  
  at fn (./node_modules/nuxt/dist/app/nuxt.js:208:44)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)  
  at ./node_modules/nuxt/dist/app/nuxt.js:210:56  
  at Object.runWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3855:18)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:210:24)  
  at Object.runWithContext (./node_modules/nuxt/dist/app/nuxt.js:32:29) (repeated 4 times)
```

If I commend out the supabase module in config app works

**Comment by nabakdev** [comment]
faced the same issue, but when I downgraded to version 0.3.5, the problem disappeared

**Comment by larbish** [comment]
Should be fixed in last version. Could you have a check ? 🙏
