### ISSUE TITLE
Please help. production project not compiling after upgrade

### ISSUE THREAD

**Issue by CareTiger** [nuxt-modules/supabase#223]
```
Vite client warmed up in 5703ms                                                                                                                                                            3:53:18 PM
✔ Nitro built in 3791 ms                                                                                                                                                               nitro 3:53:20 PM
[nuxt] [request error] [unhandled] [500] createError is not defined                                                                                                                           3:53:21 PM
  at serverSupabaseUser (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/.nuxt/dev/index.mjs:1224:5)                                                                               3:53:06 PM  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.handler (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/.nuxt/dev/index.mjs:1231:16)
  at async Object.handler (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/h3/dist/index.mjs:1284:19)
  at async toNodeHandle (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/h3/dist/index.mjs:1359:7)
  at async ufetch (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:206:26)
  at async $fetch2 (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)
  at async /C:/Users/Ven/Documents/github-c-drive/project-juniper/app/.nuxt/dev/index.mjs:928:17
[nuxt] [request error] [unhandled] [500] createError is not defined                                                                                                                           3:53:21 PM  
  at serverSupabaseUser (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/.nuxt/dev/index.mjs:1224:5)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.handler (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/.nuxt/dev/index.mjs:1231:16)
  at async Object.handler (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/h3/dist/index.mjs:1284:19)
  at async toNodeHandle (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/h3/dist/index.mjs:1359:7)
  at async ufetch (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:206:26)
  at async $fetchRaw2 (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:234:14)
  at async $fetch2 (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)
  at async /C:/Users/Ven/Documents/github-c-drive/project-juniper/app/.nuxt/dev/index.mjs:928:17
```

### Version
```
Nuxt project info:                                                                                                                                                                            4:11:57 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.0
- Builder:          vite
- User Config:      extends, devtools, vite, nitro, routeRules, site, webVitals, typescript, colorMode, app, modules, sanity, image, googleFonts, linkChecker, runtimeConfig
- Runtime Modules:  @nuxt/devtools@0.7.4, @nuxtjs/supabase@1.0.0, @nuxtjs/google-fonts@3.0.2, @nuxthq/ui@2.7.0-28181796.b696b15, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, @nuxtjs/web-vitals@0.2.6, @nuxtjs/fontaine@0.4.1, @nuxt/content@2.7.2, @nuxtjs/sanity@1.8.0, @nuxt/image@1.0.0-rc.1
- Build Modules:    -
------------------------------>

```
### Steps to reproduce
upgrade to laltest version

### What is Expected?
code should not break because of upgrade to a "stable" version
```
createError is not defined                                                                                                                           3:53:21 PM
  at serverSupabaseUser (/C:/Users/Ven/Documents/github-c-drive/project-juniper/app/.nuxt/dev/index.mjs:1224:5)     
```

**Comment by Aietes** [comment]
It seems there is simply an import missing. This will be a quick fix.
