### ISSUE TITLE
when i update v1.0.1, deployment enviroment dosen't work

### ISSUE THREAD

**Issue by yeonjulee1005** [nuxt-modules/supabase#229]
i update @nuxrt/supabase 1.0.1 

it works fine in dev enviroment. 

but, when it deploy, page dosen't work like this

<img width="962" alt="image" src="https://github.com/nuxt-modules/supabase/assets/57179957/bd769b30-ddd2-43c7-a83e-4d9ec25b3d14">

<img width="746" alt="image" src="https://github.com/nuxt-modules/supabase/assets/57179957/980aa11e-7a70-4304-91b3-7239cfce9f7d">

also, i check `nuxt preview` 

terminal says, like this 

```
[nuxt] [request error] [unhandled] [500] Cannot access 'NuxtPluginIndicator' before initialization
  at defineNuxtPlugin (./server/chunks/app/server.mjs:51962:19)
  at ./server/chunks/app/server.mjs:1984:52
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

<img width="815" alt="image" src="https://github.com/nuxt-modules/supabase/assets/57179957/e8cfc5a7-414a-455a-87a1-e699fb7c000c">

first, i rollback this version.

how should i do? please help me~~

**Comment by onurusluca** [comment]
@yeonjulee1005 Just to confirm, have you read the [release notes](https://github.com/nuxt-modules/supabase/releases/tag/v1.0.1) and made the required changes?

**Comment by yeonjulee1005** [comment]
@onurusluca thank you for your kind reply :)

sure! i've done like this. `nuxt.config.ts`

![image](https://github.com/nuxt-modules/supabase/assets/57179957/e064408c-68c0-459b-b931-c4eaf10e0a6d)

and also set promise in `serverSupabaseClient` like this
(this is some example)

`/server/api/user`
![image](https://github.com/nuxt-modules/supabase/assets/57179957/aaa74467-1686-4141-9ec4-c178ed61633e)


and i changed `useSupabaseAuthClient` to `useSupabaseClient`


but, it dosen't work in deployment environment 
(it works fine in dev environment)

<img width="501" alt="image" src="https://github.com/nuxt-modules/supabase/assets/57179957/63fe2fc9-ac7d-4a1f-934d-68a3f3d09f94">
<img width="382" alt="image" src="https://github.com/nuxt-modules/supabase/assets/57179957/30dabde7-dd04-4225-9ab3-e217e24fe0a2">

**Comment by onurusluca** [comment]
@yeonjulee1005 
The fact that i works in dev but not deployment gives us a pretty good starting point.
First, do a local build and see if that works there. If that works, it is probably a environment variables problem or a hosting one.
Where are you hosting? 

What is Fo btw? Is that your custom code? Where do you use it?

Also just in case do a nuxt and npm cache clean.

**Comment by yeonjulee1005** [comment]
@onurusluca 

i hosting in `vercel` but, in vercel enviroment are like this
<img width="954" alt="image" src="https://github.com/nuxt-modules/supabase/assets/57179957/16d93a3a-120e-40f9-80dc-0c40c1f58068">

but, it works fine `@nuxt/supabase 0.3.8`
when i upgrade `@nuxt/supabase 1.0.1`  it occur.


--- 

actually, i try `nuxt build` -> `nuxt preview` in local.
But as mentioned above, 
terminal output below error.

```
[nuxt] [request error] [unhandled] [500] Cannot access 'NuxtPluginIndicator' before initialization
  at defineNuxtPlugin (./server/chunks/app/server.mjs:51962:19)
  at ./server/chunks/app/server.mjs:1984:52
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

i guess  `Fo` is  `NuxtPluginIndicator` 👀 

--- 

and i try `yarn cleanup` and `yarn cahce clean`, and deleted `.nuxt` `.node_modules`
it dosen't work.. 😢

**Comment by onurusluca** [comment]
@yeonjulee1005 Hmm, then it must be a specific problem. Can you provide a reproduction or is it possible to see your code?

**Comment by yeonjulee1005** [comment]
@onurusluca 
sure! my project is currently open source below, you can show my source code:)

[Dooramgi](https://github.com/yeonjulee1005/dooramgi)

**Comment by onurusluca** [comment]
@yeonjulee1005 Thanks for sharing, nice code base!

Because it says `defineNuxtPlugin`, maybe try to comment out the plugins one by one and see if it works?

I can't really test it because I need to have a supabase backend to use it. Sorry, I can't really find a problem here. 

**If possible a reproduction is welcome.**

Also this may be a nuxt supabase lib internal problem. Try tagging the maintainers but I am sure they will want a reproduction.

> 
> To determine the cause of the issue, can you provide a minimal minimal reproduction using one of the starter templates?
> 
> 👉 https://stackblitz.com/github/nuxt/starter/tree/v3-stackblitz
> 👉 https://codesandbox.io/s/github/nuxt/starter/v3-codesandbox

**Comment by yeonjulee1005** [comment]
@onurusluca  
thank you for helping me :)
