### ISSUE TITLE
Auth session missing on password reset flow

### ISSUE THREAD

**Issue by nosizejosh** [nuxt-modules/supabase#262]
### Version
@nuxtjs/supabase: "^1.0.2"
nuxt:  "^3.7.0"

After one successful password reset, I am unable to reset password of either the same user or other users. I get a failed to fetch error on the client and Auth session missing error on the console. 

forgot p[password code
```
const client = useSupabaseClient()
const { error }  = await client.auth.resetPasswordForEmail(email.value, {
    redirectTo: `${useRuntimeConfig().public.baseUrl}/auth/new-password`    
  })
```

new password code
```
const client = useSupabaseClient()
 const { error }  = await client.auth.updateUser({
    password: password.value
  })
  await client.auth.signOut()
```

Anyone able to complete this flow successfully?

### Steps to reproduce
On redirect from supabase to the new-password page, this is the error on the console. 
![image](https://github.com/nuxt-modules/supabase/assets/392227/71dd657c-ad96-42b8-ae72-4bbc743035cb)
When user enters the new password and submits, user receives a failed to fetch error and below is error shows on the console.
![image](https://github.com/nuxt-modules/supabase/assets/392227/9c032f42-58a4-4ae2-ad19-9836fb5b1cec)

### What is Expected?
User will be able to go through entire flow and reset their password

### What is actually happening?
User unable to complete flow. Flow worked once and after that has been failing with the errors as shown above.

**Comment by kyng-cytro** [comment]
Any workaround or fix yet?

**Comment by nosizejosh** [comment]
> Any workaround or fix yet?

no none yet. Do you have a solution?

**Comment by kyng-cytro** [comment]
> > Any workaround or fix yet?
> 
> no none yet. Do you have a solution?

No and mine just got worse. Just noticed session doesn't refresh. Once it dies user is sent back to login page. Even while using the app.

**Comment by kyng-cytro** [comment]
> > > Any workaround or fix yet?
> > 
> > no none yet. Do you have a solution?
> 
> No and mine just got worse. Just noticed session doesn't refresh. Once it dies user is sent back to login page. Even while using the app.

Ok now I switched to the new flow. I mean the login / confirm flow. And it's a bit better. Auth only dies some times. But reset still doesn't work.

**Comment by ErwinAI** [comment]
I'm having the same problem. It's not a very good sign that this breaks while trying Supabase for the first time 😓 

Versions:
```
"nuxt": "^3.7.3"
"@nuxtjs/supabase": "^1.1.0"
```

I've tried both the SPA and the SSR route. Both give the same error.
https://supabase.com/docs/guides/auth/auth-password-reset

### SPA 

reset.vue
```
const supabase = useSupabaseClient()
const email = ref('')
const redirectToSPA = `${useRuntimeConfig().public.absoluteBaseUrl}/account/manage`

const resetPassword = async () => {
  loading.value = true

  const { error, data } = await supabase.auth.resetPasswordForEmail(email.value, { redirectToSPA })
  if (data) {
    console.log(data)
  }
  if (error) {
    console.log(error)
  }
}
```

manage.vue:
```
const supabase = useSupabaseClient()
await supabase.auth.updateUser({ password: 'something' }).then((result) => {
  console.log(result)
})
```

Interestingly I get this console error:
```
Failed to load resource: the server responded with a status of 403 ()
https://pbdxvyevrcyaszqkyonm.supabase.co/auth/v1/token?grant_type=pkce
```

And this error log indicating a missing 'auth':
```
AuthSessionMissingError: Auth session missing!
    at http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-KGNBDVEI.js?v=59e0fd59:1547:17
    at SupabaseAuthClient._useSession (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-KGNBDVEI.js?v=59e0fd59:1440:20)
    at async SupabaseAuthClient._updateUser (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-KGNBDVEI.js?v=59e0fd59:1541:14)
    at async http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-KGNBDVEI.js?v=59e0fd59:1536:14
    at async http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-KGNBDVEI.js?v=59e0fd59:1393:18
```

SSR:

reset.vue
```
const supabase = useSupabaseClient()
const email = ref('')
const redirectToSSR = `${useRuntimeConfig().public.absoluteBaseUrl}/api/auth/callback?to=/account/manage`

const resetPassword = async () => {
  loading.value = true

  const { error, data } = await supabase.auth.resetPasswordForEmail(email.value, { redirectToSSR })
  if (data) {
    console.log(data)
  }
  if (error) {
    console.log(error)
  }
}
```

callback.js in /server/api/auth

```
import { serverSupabaseClient } from '#supabase/server'
export default eventHandler(async (event) => {
  console.log('api callback..')
  const code = event.context.params.code
  const to = event.context.params.to
  const supabase = await serverSupabaseClient(event)
  
  // call the Supabase API to exchange the code for a session
  await supabase.auth.exchangeCodeForSession(code)

  console.log('redirecting you now to ' + to)
  return sendRedirect(event, to, 301)
})
```

Error on server-side:
```
{
"url": "[/api/auth/callback?code=c90c5bfd-423b-47af-af47-3571c0f87995&to=%2Faccount%2Fmanage](http://localhost:3000/api/auth/callback?code=c90c5bfd-423b-47af-af47-3571c0f87995&to=%2Faccount%2Fmanage)",
"statusCode": 400,
"statusMessage": "",
"message": "invalid request: both auth code and code verifier should be non-empty",
"stack": "<pre><span class=\"stack internal\">at handleError (C:\\Users\\me\\projects\\x\\node_modules\\@supabase\\gotrue-js\\src\\lib\\fetch.ts:49:9)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at _handleRequest (C:\\Users\\me\\projects\\x\\node_modules\\@supabase\\gotrue-js\\src\\lib\\fetch.ts:128:5)</span>\n<span class=\"stack internal\">at _request (C:\\Users\\me\\projects\\x\\node_modules\\@supabase\\gotrue-js\\src\\lib\\fetch.ts:95:16)</span>\n<span class=\"stack internal\">at SupabaseAuthClient._exchangeCodeForSession (C:\\Users\\me\\projects\\x\\node_modules\\@supabase\\gotrue-js\\src\\GoTrueClient.ts:502:29)</span></pre>"
}
```

What is this auth session? And how can I make this work?

**Comment by ErwinAI** [comment]
@silentworks had a good comment in another repo: this auth flow (PKCE) only works if you open the link on the same browser/device because it uses cookies.

Unfortunately, that issue is now closed. And I have tried to make this work with the same browser+device. This leaves me to think that this issue is with this module and the way it handles that cookie.

**Comment by chz8494** [comment]
isn't it because `In order to use the  updateUser() method, the user needs to be signed in first`?
https://supabase.com/docs/reference/javascript/auth-updateuser

**Comment by ErwinAI** [comment]
@chz8494 When going through the password reset flow, the user is not logged in, but will temporarily be identified by a code that's in the URL as a parameter when they click through from the 'password forgotten' email. This allows the use of `updateUser()` as well.

**Comment by nosizejosh** [comment]
Is there anyone here who has been able to successfully implement forgot password flow with this package?  
Please share how you were able to achieve it?

Thanks

**Comment by chz8494** [comment]
> @chz8494 When going through the password reset flow, the user is not logged in, but will temporarily be identified by a code that's in the URL as a parameter when they click through from the 'password forgotten' email. This allows the use of `updateUser()` as well.

I know the temp token supposed to give user who clicked reset link a temp access so that `updateUser()` can be called. But I don't think this is working, and that's why we are seeing `Auth session missing!`

**Comment by liamcharmer** [comment]
Any updates? Or any working example?

**Comment by nosizejosh** [comment]
now the error I get  in the url when email link is clicked

`error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired#error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired`


Please can you provide a working code sample so we can follow?

**Comment by chz8494** [comment]
Mine actually just started working now, user can get tokens and session after clicking reset link

**Comment by nosizejosh** [comment]
@chz8494 please share a repo.

I got it to work today, but just once for one user. after that it doesn't work for any user including the one that worked before.

**Comment by nosizejosh** [comment]
please any one with updates or a working example?

**Comment by Shooteger** [comment]
I can confirm, password reset works only in the same browser-device for me. Password link get sent, as long as I open for example Gmail, then click on the link in the same browser window it works. When I change device to click on the link in my email or on another browser on same device, I get the same Auth Session Error... Very bad indeed. Maybe I will open PR to fix this soon. This is definitely a bug in the package.

**Comment by MalachiDraven** [comment]
I'm getting the same error about the auth session missing. This is unacceptable. The documentation for this nuxt module is awful.
