### ISSUE TITLE
After logging in, use serverSupabaseUser api and report a 500 exception

### ISSUE THREAD

**Issue by liuxingyu521** [nuxt-modules/supabase#387]
### Version
@nuxtjs/supabase:   1.3.4
nuxt:  3.12.3

### Reproduction Link
https://github.com/liuxingyu521/nuxt-module-supabase-auth-login-refresh-issue

### Steps to reproduce
1. click login button and login successful
2. click getUser button and then show `500` exception, error message below.
```json
{
    "url": "/api/getUser",
    "statusCode": 500,
    "statusMessage": "fetch failed",
    "message": "fetch failed",
    "stack": "<pre><span class=\"stack internal\">at createError (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:78:15)</span>\n<span class=\"stack internal\">at serverSupabaseUser (./node_modules/.pnpm/@nuxtjs+supabase@1.3.4/node_modules/@nuxtjs/supabase/dist/runtime/server/services/serverSupabaseUser.js:7:11)</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack\">at Object.handler (./server/api/getUser.ts:4:1)</span>\n<span class=\"stack internal\">at async ./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:19</span>\n<span class=\"stack internal\">at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)</span></pre>"
}
```
![image](https://github.com/nuxt-modules/supabase/assets/15321445/1472d0de-8092-4dcc-a444-a6e100bb5034)

### What is Expected?
getUser successful

### What is actually happening?
report 500 error

**Comment by liuxingyu521** [comment]
Sorry, I finally found out that it was my local network problem. 
When I solve the network problem, the process is work expected. I will close this issue.
