### ISSUE TITLE
Nuxt build broken when using nuxtjs/supabase

### ISSUE THREAD

**Issue by ZanzibarNuclear** [nuxt-modules/supabase#425]
### Version
@nuxtjs/supabase: v1.4.1
nuxt: v3.13.2

### Steps to reproduce

Install and use nuxtjs/supabase. Works fine in dev mode. Build with:

npm run build

Nuxt Build Error: [commonjs--resolver] Missing "./client" specifier in "@ nuxtjs/supabase" package

at e (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:45979:25)
  at n (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:45979:627)
  at o (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:45979:1297)
  at resolveExportsOrImports (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46600:18)
  at resolveDeepImport (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46623:25)
  at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46388:16)
  at Object.resolveId (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:46138:19)
  at node_modules/rollup/dist/es/shared/node-entry.js:20730:40
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:20630:28)
  at async resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19234:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19663:15)
  at async Object.resolveId (node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:12833:10)
  at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:20630:28)
  at async resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19234:26)
  at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19663:15)
  at async node_modules/rollup/dist/es/shared/node-entry.js:19966:50

### What is actually happening?

When I try to build either locally or as part of Cloudflare deployment, I get the following error:

Nuxt Build Error: [commonjs--resolver] Missing "./client" specifier in "@ nuxtjs/supabase" package

'npm run dev' works fine, and I have no problems accessing Supabase from the SPA. I am using OAuth2.

nuxt.config.ts includes @ nuxtjs/supabase in the list of modules, and has this:

  supabase: {
    redirect: true,
    redirectOptions: {
      login: '/join',
      callback: '/confirm-auth',
      cookieRedirect: true,
      exclude: ['/', '/join', '/confirm-auth'],
    },
    cookieName: 'won-token',
    cookieOptions: {
      maxAge: 60 * 60 * 8,
      sameSite: 'lax',
      secure: true
    },
    clientOptions: {
      auth: {
        flowType: 'pkce',
        detectSessionInUrl: true,
        persistSession: true,
        autoRefreshToken: true
      }
    }
  },

The build error happens even without the supabase config (with redirect: false).

I have tried deleting node_modules and package-lock.json, then rebuilding. Same problem.

Any other ideas?

**Comment by th1m0** [comment]
Could you please provide a reproduction repo? I'm not able to reproduce this right now.

**Comment by ZanzibarNuclear** [comment]
Here's the repo and branch: https://github.com/ZanzibarNuclear/flux-client/tree/fill-gaps-to-alpha

**Comment by evertontst** [comment]
I have the same problem here. What's the solution?

**Comment by ZanzibarNuclear** [comment]
It's a real blocker. My solution is to stop using Supabase.
